#!/usr/bin/env python3
from __future__ import annotations
import argparse, os, shutil, subprocess, sys, tarfile, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORK = ROOT / 'experiments/static-wasi-python'
SRC = WORK / 'Python-3.12.0'
TGZ = WORK / 'Python-3.12.0.tgz'
PY_URL = 'https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz'
WASMTIME = ROOT / 'experiments/wasi-python-spike/wasmtime/wasmtime-v18.0.4-x86_64-linux/wasmtime'
WASI_SDK = Path.home() / '.local/share/wasmpy-build/wasi-sdk'
THIRD_PARTY_PREFIX = WORK / 'third-party-wasi'

SETUP_LOCAL = '''# Generated by scripts/static_wasi/build_static_wasi_python.py.
# WASI target policy: no dynamic extension modules.  The Android/Chicory path
# needs one self-contained python.wasm, so third-party C extensions are added
# here as builtin/static modules instead of .so/.wasm extension files.
#
# CPython 3.12's wasm32-wasi build already makes stdlib extension modules
# static by default.  These test/limited-ABI modules are marked shared in
# Modules/Setup.stdlib.in; disable them so `make all` never invokes wasm-ld as
# a dynamic-extension linker.
*disabled*
_testimportmultiple
_testmultiphase
_testsinglephase
xxlimited
xxlimited_35
'''


def run(cmd, *, cwd=None, env=None, check=True):
    print('+', ' '.join(map(str, cmd)))
    return subprocess.run(list(map(str, cmd)), cwd=cwd, env=env, check=check)


def ensure_source():
    WORK.mkdir(parents=True, exist_ok=True)
    if not TGZ.exists():
        urllib.request.urlretrieve(PY_URL, TGZ)
    if not SRC.exists():
        with tarfile.open(TGZ) as t:
            t.extractall(WORK)


def ensure_wasmtime():
    if WASMTIME.exists():
        return
    run([sys.executable, str(ROOT / 'experiments/wasi_python_probe.py')], check=False)
    if not WASMTIME.exists():
        raise SystemExit(f'wasmtime not found at {WASMTIME}')


def env():
    if not (WASI_SDK / 'bin/clang').exists():
        raise SystemExit(f'WASI SDK not found at {WASI_SDK}; install wasmpy-build first')
    e = os.environ.copy()
    e['WASI_SDK_PATH'] = str(WASI_SDK)
    e['PATH'] = f'{WASMTIME.parent}:{WASI_SDK / "bin"}:{e["PATH"]}'
    return e


def write_setup_local():
    (SRC / 'Modules/Setup.local').write_text(SETUP_LOCAL)
    # wasm_build.py creates the builddir copy only during configure; if we are
    # iterating after configure, keep the generated build copy in sync and force
    # makesetup to regenerate Makefile module lists.
    bcopy = SRC / 'builddir/wasi/Modules/Setup.local'
    if bcopy.parent.exists():
        bcopy.write_text(SETUP_LOCAL)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--clean', action='store_true', help='clean CPython wasm build before building')
    args = ap.parse_args()
    ensure_source(); ensure_wasmtime(); write_setup_local()
    base_env = env()
    # Build host Python without WASI-only third-party library paths; otherwise
    # native gcc may accidentally try to link wasm32 archives.
    host_cmd = [sys.executable, './Tools/wasm/wasm_build.py']
    if args.clean:
        host_cmd.append('--clean')
    host_cmd += ['build', 'build']
    run(host_cmd, cwd=SRC, env=base_env)

    target_env = base_env.copy()
    if THIRD_PARTY_PREFIX.exists():
        inc = THIRD_PARTY_PREFIX / 'include'
        lib = THIRD_PARTY_PREFIX / 'lib'
        pc = lib / 'pkgconfig'
        target_env['CPPFLAGS'] = f'-I{inc} ' + target_env.get('CPPFLAGS', '')
        target_env['LDFLAGS'] = f'-L{lib} ' + target_env.get('LDFLAGS', '')
        target_env['PKG_CONFIG_PATH'] = str(pc)
    if args.clean:
        shutil.rmtree(SRC / 'builddir/wasi', ignore_errors=True)
    # Configure may recreate builddir/wasi/Modules/Setup.local from an empty
    # generated file, so run configure first, re-apply our static policy, then
    # compile.
    run([sys.executable, './Tools/wasm/wasm_build.py', 'wasi', 'configure'], cwd=SRC, env=target_env)
    write_setup_local()
    run([sys.executable, './Tools/wasm/wasm_build.py', '--clean', 'wasi', 'compile'], cwd=SRC, env=target_env)
    print(SRC / 'builddir/wasi/python.wasm')

if __name__ == '__main__':
    main()
