#!/usr/bin/env python3
from __future__ import annotations
import argparse, os, shutil, subprocess, sys, tarfile, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORK = ROOT / 'experiments/static-wasi-python'
SRC = WORK / 'Python-3.12.0'
TGZ = WORK / 'Python-3.12.0.tgz'
PY_URL = 'https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz'
WASMTIME = ROOT / 'experiments/wasi-python-spike/wasmtime/wasmtime-v18.0.4-x86_64-linux/wasmtime'
WASI_SDK = Path.home() / '.local/share/wasmpy-build/wasi-sdk'
THIRD_PARTY_PREFIX = WORK / 'third-party-wasi'
THIRD_PARTY_SRC = WORK / 'third-party-src'
THIRD_PARTY_BUILD = WORK / 'third-party-build'
THIRD_PARTY_SITE = WORK / 'third-party-site'
REGEX_TGZ = THIRD_PARTY_SRC / 'regex-2024.11.6.tar.gz'
REGEX_URL = 'https://files.pythonhosted.org/packages/source/r/regex/regex-2024.11.6.tar.gz'
MSGPACK_TGZ = THIRD_PARTY_SRC / 'msgpack-1.1.1.tar.gz'
MSGPACK_URL = 'https://files.pythonhosted.org/packages/source/m/msgpack/msgpack-1.1.1.tar.gz'
LXML_TGZ = THIRD_PARTY_SRC / 'lxml-5.3.0.tar.gz'
LXML_URL = 'https://files.pythonhosted.org/packages/source/l/lxml/lxml-5.3.0.tar.gz'
PILLOW_TGZ = THIRD_PARTY_SRC / 'pillow-11.3.0.tar.gz'
PILLOW_URL = 'https://files.pythonhosted.org/packages/source/p/pillow/pillow-11.3.0.tar.gz'

SETUP_LOCAL_HEADER = '''# Generated by scripts/static_wasi/build_static_wasi_python.py.
# WASI target policy: no dynamic extension modules.  The Android/Chicory path
# needs one self-contained python.wasm, so third-party C extensions are added
# here as builtin/static modules instead of .so/.wasm extension files.
#
# CPython 3.12's wasm32-wasi build already makes stdlib extension modules
# static by default.  These test/limited-ABI modules are marked shared in
# Modules/Setup.stdlib.in; disable them so `make all` never invokes wasm-ld as
# a dynamic-extension linker.
*disabled*
_testimportmultiple
_testmultiphase
_testsinglephase
xxlimited
xxlimited_35
'''.rstrip() + '\n'

def run(cmd, *, cwd=None, env=None, check=True):
    print('+', ' '.join(map(str, cmd)))
    return subprocess.run(list(map(str, cmd)), cwd=cwd, env=env, check=check)

def ensure_source():
    WORK.mkdir(parents=True, exist_ok=True)
    if not TGZ.exists():
        urllib.request.urlretrieve(PY_URL, TGZ)
    if not SRC.exists():
        with tarfile.open(TGZ) as t:
            t.extractall(WORK)

def ensure_wasmtime():
    if WASMTIME.exists():
        return
    run([sys.executable, str(ROOT / 'experiments/wasi_python_probe.py')], check=False)
    if not WASMTIME.exists():
        raise SystemExit(f'wasmtime not found at {WASMTIME}')

def regex_source_dir() -> Path:
    return THIRD_PARTY_BUILD / 'regex-2024.11.6'

def msgpack_source_dir() -> Path:
    return THIRD_PARTY_BUILD / 'msgpack-1.1.1'

def lxml_source_dir() -> Path:
    return THIRD_PARTY_BUILD / 'lxml-5.3.0'

def pillow_source_dir() -> Path:
    return THIRD_PARTY_BUILD / 'pillow-11.3.0'

def ensure_pillow_source():
    THIRD_PARTY_SRC.mkdir(parents=True, exist_ok=True)
    THIRD_PARTY_BUILD.mkdir(parents=True, exist_ok=True)
    if not PILLOW_TGZ.exists():
        urllib.request.urlretrieve(PILLOW_URL, PILLOW_TGZ)
    dest = pillow_source_dir()
    if not dest.exists():
        with tarfile.open(PILLOW_TGZ) as t:
            t.extractall(THIRD_PARTY_BUILD)

def ensure_lxml_source():
    THIRD_PARTY_SRC.mkdir(parents=True, exist_ok=True)
    THIRD_PARTY_BUILD.mkdir(parents=True, exist_ok=True)
    if not LXML_TGZ.exists():
        urllib.request.urlretrieve(LXML_URL, LXML_TGZ)
    dest = lxml_source_dir()
    if not dest.exists():
        with tarfile.open(LXML_TGZ) as t:
            t.extractall(THIRD_PARTY_BUILD)

def ensure_msgpack_source():
    THIRD_PARTY_SRC.mkdir(parents=True, exist_ok=True)
    THIRD_PARTY_BUILD.mkdir(parents=True, exist_ok=True)
    if not MSGPACK_TGZ.exists():
        urllib.request.urlretrieve(MSGPACK_URL, MSGPACK_TGZ)
    dest = msgpack_source_dir()
    if not dest.exists():
        with tarfile.open(MSGPACK_TGZ) as t:
            t.extractall(THIRD_PARTY_BUILD)

def ensure_regex_source():
    THIRD_PARTY_SRC.mkdir(parents=True, exist_ok=True)
    THIRD_PARTY_BUILD.mkdir(parents=True, exist_ok=True)
    if not REGEX_TGZ.exists():
        urllib.request.urlretrieve(REGEX_URL, REGEX_TGZ)
    dest = regex_source_dir()
    if not dest.exists():
        with tarfile.open(REGEX_TGZ) as t:
            t.extractall(THIRD_PARTY_BUILD)



def pillow_c_sources():
    imaging = ['decode', 'encode', 'map', 'display', 'outline', 'path']
    lib_imaging = [
        'Access','AlphaComposite','Arrow','Resample','Reduce','Bands','BcnDecode','BcnEncode',
        'BitDecode','Blend','Chops','ColorLUT','Convert','ConvertYCbCr','Copy','Crop','Dib',
        'Draw','Effects','EpsEncode','File','Fill','Filter','FliDecode','Geometry','GetBBox',
        'GifDecode','GifEncode','HexDecode','Histo','JpegDecode','JpegEncode','Matrix','ModeFilter',
        'Negative','Offset','Pack','PackDecode','Palette','Paste','Quant','QuantOctree','QuantHash',
        'QuantHeap','PcdDecode','PcxDecode','PcxEncode','Point','RankFilter','RawDecode','RawEncode',
        'Storage','SgiRleDecode','SunRleDecode','TgaRleDecode','TgaRleEncode','Unpack','UnpackYCC',
        'UnsharpMask','XbmDecode','XbmEncode','ZipDecode','ZipEncode','TiffDecode','Jpeg2KDecode',
        'Jpeg2KEncode','BoxBlur','QuantPngQuant','codec_fd',
    ]
    src = pillow_source_dir() / 'src'
    pairs = [(src / '_imaging.c', 'wasi_pil_imaging.c')]
    pairs += [(src / f'{name}.c', f'wasi_pil_{name}.c') for name in imaging]
    pairs += [(src / 'libImaging' / f'{name}.c', f'wasi_pil_{name}.c') for name in lib_imaging]
    return pairs

def stage_pillow_package():
    src = pillow_source_dir() / 'src/PIL'
    dest = THIRD_PARTY_SITE / 'PIL'
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, dest, ignore=shutil.ignore_patterns('__pycache__'))
    for mod in ['_imaging', '_imagingft', '_imagingcms', '_webp', '_avif', '_imagingmath', '_imagingmorph']:
        (dest / f'{mod}.py').write_text(f"import sys as _sys\nimport {mod} as _m\n_sys.modules[__name__] = _m\n")
    for source, staged in pillow_c_sources():
        out = SRC / f'Modules/{staged}'
        shutil.copy2(source, out)
        if source.name == '_imaging.c':
            data = '#ifndef PILLOW_VERSION\n#define PILLOW_VERSION "11.3.0"\n#endif\n' + out.read_text()
            noargs = ['_getpalettemode', '_isblock', '_getextrema', '_getprojection', '_split', '_chop_invert']
            for name in noargs:
                data = data.replace(f'static PyObject *\n{name}(ImagingObject *self) {{', f'static PyObject *\n{name}_impl(ImagingObject *self) {{')
            decls = ''.join(f'static PyObject *{name}(ImagingObject *, PyObject *);\n' for name in noargs)
            data = data.replace('static PyTypeObject Imaging_Type;', 'static PyTypeObject Imaging_Type;\n' + decls)
            data += ''.join(f'\nstatic PyObject *\n{name}(ImagingObject *self, PyObject *Py_UNUSED(ignored)) {{\n    return {name}_impl(self);\n}}\n' for name in noargs)
            out.write_text(data)
        elif source.name == 'encode.c':
            data = out.read_text()
            data = data.replace('static PyObject *\n_encode_to_pyfd(ImagingEncoderObject *encoder) {', 'static PyObject *\n_encode_to_pyfd_impl(ImagingEncoderObject *encoder) {')
            data = data.replace('static PyTypeObject ImagingEncoderType;', 'static PyTypeObject ImagingEncoderType;\nstatic PyObject *_encode_to_pyfd(ImagingEncoderObject *, PyObject *);')
            data += '\nstatic PyObject *\n_encode_to_pyfd(ImagingEncoderObject *encoder, PyObject *Py_UNUSED(ignored)) {\n    return _encode_to_pyfd_impl(encoder);\n}\n'
            out.write_text(data)
    for source, staged in {
        '_imagingft.c': 'wasi_pil_imagingft.c',
        '_imagingcms.c': 'wasi_pil_imagingcms.c',
        '_webp.c': 'wasi_pil_webp.c',
        '_avif.c': 'wasi_pil_avif.c',
        '_imagingmath.c': 'wasi_pil_imagingmath.c',
        '_imagingmorph.c': 'wasi_pil_imagingmorph.c',
    }.items():
        out = SRC / f'Modules/{staged}'
        shutil.copy2(pillow_source_dir() / 'src' / source, out)
        if source == '_webp.c':
            # _imaging.c exports the same helpers. They would be harmless in
            # separately-loaded extension modules, but static builtins share one
            # link namespace, so keep _webp's copies private/renamed.
            data = out.read_text()
            data = data.replace('ImagingSectionEnter', 'WebPImagingSectionEnter')
            data = data.replace('ImagingSectionLeave', 'WebPImagingSectionLeave')
            # Pillow's _webp uses one-argument METH_NOARGS callbacks. CPython
            # accepts this on native platforms but wasm tables enforce exact
            # indirect-call signatures, so provide proper two-argument wrappers.
            data = data.replace('PyObject *\n_anim_decoder_get_info(PyObject *self) {', 'static PyObject *\n_anim_decoder_get_info_impl(PyObject *self) {')
            data = data.replace('PyObject *\n_anim_decoder_get_next(PyObject *self) {', 'static PyObject *\n_anim_decoder_get_next_impl(PyObject *self) {')
            data = data.replace('PyObject *\n_anim_decoder_reset(PyObject *self) {', 'static PyObject *\n_anim_decoder_reset_impl(PyObject *self) {')
            data = data.replace('#include <webp/demux.h>', '#include <webp/demux.h>\nstatic PyObject *_anim_decoder_get_info(PyObject *, PyObject *);\nstatic PyObject *_anim_decoder_get_next(PyObject *, PyObject *);\nstatic PyObject *_anim_decoder_reset(PyObject *, PyObject *);')
            data += '\nstatic PyObject *\n_anim_decoder_get_info(PyObject *self, PyObject *Py_UNUSED(ignored)) {\n    return _anim_decoder_get_info_impl(self);\n}\nstatic PyObject *\n_anim_decoder_get_next(PyObject *self, PyObject *Py_UNUSED(ignored)) {\n    return _anim_decoder_get_next_impl(self);\n}\nstatic PyObject *\n_anim_decoder_reset(PyObject *self, PyObject *Py_UNUSED(ignored)) {\n    return _anim_decoder_reset_impl(self);\n}\n'
            out.write_text(data)
        elif source == '_imagingft.c':
            data = out.read_text()
            data = data.replace('static PyObject *\nfont_getvarnames(FontObject *self) {', 'static PyObject *\nfont_getvarnames_impl(FontObject *self) {')
            data = data.replace('static PyObject *\nfont_getvaraxes(FontObject *self) {', 'static PyObject *\nfont_getvaraxes_impl(FontObject *self) {')
            data = data.replace('static PyTypeObject Font_Type;', 'static PyTypeObject Font_Type;\nstatic PyObject *font_getvarnames(FontObject *, PyObject *);\nstatic PyObject *font_getvaraxes(FontObject *, PyObject *);')
            data += '\nstatic PyObject *\nfont_getvarnames(FontObject *self, PyObject *Py_UNUSED(ignored)) {\n    return font_getvarnames_impl(self);\n}\nstatic PyObject *\nfont_getvaraxes(FontObject *self, PyObject *Py_UNUSED(ignored)) {\n    return font_getvaraxes_impl(self);\n}\n'
            out.write_text(data)
        elif source == '_avif.c':
            data = out.read_text()
            data = data.replace('PyObject *\n_codec_versions(PyObject *self, PyObject *args) {', 'static PyObject *\n_codec_versions_impl(PyObject *self, PyObject *args) {')
            data = data.replace('PyObject *\n_encoder_finish(AvifEncoderObject *self) {', 'static PyObject *\n_encoder_finish_impl(AvifEncoderObject *self) {')
            data = data.replace('PyObject *\n_decoder_get_info(AvifDecoderObject *self) {', 'static PyObject *\n_decoder_get_info_impl(AvifDecoderObject *self) {')
            data = data.replace('PyObject *\n_encoder_dealloc(AvifEncoderObject *self) {', 'static void\n_encoder_dealloc(AvifEncoderObject *self) {')
            data = data.replace('PyObject *\n_decoder_dealloc(AvifDecoderObject *self) {', 'static void\n_decoder_dealloc(AvifDecoderObject *self) {')
            data = data.replace('    PyBuffer_Release(&self->buffer);\n    Py_RETURN_NONE;\n}', '    PyBuffer_Release(&self->buffer);\n    Py_TYPE(self)->tp_free((PyObject *)self);\n}')
            data = data.replace('    }\n    if (self->image) {\n        avifImageDestroy(self->image);\n    }\n    Py_RETURN_NONE;\n}', '    }\n    if (self->image) {\n        avifImageDestroy(self->image);\n    }\n    Py_TYPE(self)->tp_free((PyObject *)self);\n}')
            data = data.replace('static PyTypeObject AvifDecoder_Type;', 'static PyTypeObject AvifDecoder_Type;\nstatic PyObject *_codec_versions(PyObject *, PyObject *);\nstatic PyObject *_encoder_finish(AvifEncoderObject *, PyObject *);\nstatic PyObject *_decoder_get_info(AvifDecoderObject *, PyObject *);')
            data += '\nstatic PyObject *\n_codec_versions(PyObject *self, PyObject *Py_UNUSED(ignored)) {\n    return _codec_versions_impl(self, NULL);\n}\nstatic PyObject *\n_encoder_finish(AvifEncoderObject *self, PyObject *Py_UNUSED(ignored)) {\n    return _encoder_finish_impl(self);\n}\nstatic PyObject *\n_decoder_get_info(AvifDecoderObject *self, PyObject *Py_UNUSED(ignored)) {\n    return _decoder_get_info_impl(self);\n}\n'
            out.write_text(data)

def stage_lxml_package():
    src = lxml_source_dir() / 'src/lxml'
    dest = THIRD_PARTY_SITE / 'lxml'
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, dest, ignore=shutil.ignore_patterns('*.c', '*.h', '*.pxd', '*.pxi', 'tests', '__pycache__'))
    aliases = {
        'etree': '_lxml_etree',
        'objectify': '_lxml_objectify',
        '_elementpath': '_lxml_elementpath',
        'builder': '_lxml_builder',
        'sax': '_lxml_sax',
    }
    for name, builtin in aliases.items():
        (dest / f'{name}.py').write_text(
            f"import sys as _sys\nimport {builtin} as _m\n_sys.modules[__name__] = _m\n"
        )
    init_names = {
        'etree.c': ('wasi_lxml_etree.c', 'PyInit_etree', 'PyInit__lxml_etree'),
        'objectify.c': ('wasi_lxml_objectify.c', 'PyInit_objectify', 'PyInit__lxml_objectify'),
        '_elementpath.c': ('wasi_lxml_elementpath.c', 'PyInit__elementpath', 'PyInit__lxml_elementpath'),
        'builder.c': ('wasi_lxml_builder.c', 'PyInit_builder', 'PyInit__lxml_builder'),
        'sax.c': ('wasi_lxml_sax.c', 'PyInit_sax', 'PyInit__lxml_sax'),
    }
    for source, (staged, old_init, new_init) in init_names.items():
        out = SRC / f'Modules/{staged}'
        shutil.copy2(src / source, out)
        out.write_text(out.read_text().replace(old_init, new_init))

def stage_msgpack_package():
    src = msgpack_source_dir() / 'msgpack'
    dest = THIRD_PARTY_SITE / 'msgpack'
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, dest, ignore=shutil.ignore_patterns('*.c', '*.h', '*.pyx', '__pycache__'))
    init = dest / '__init__.py'
    init.write_text(init.read_text().replace('from ._cmsgpack import Packer, Unpacker, unpackb', 'from _cmsgpack import Packer, Unpacker, unpackb'))
    shutil.copy2(src / '_cmsgpack.c', SRC / 'Modules/wasi_cmsgpack.c')

def stage_regex_package():
    src = regex_source_dir() / 'regex_3'
    dest = THIRD_PARTY_SITE / 'regex'
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, dest, ignore=shutil.ignore_patterns('*.c', '*.h', 'test_regex.py', '__pycache__'))
    core = dest / '_regex_core.py'
    core.write_text(core.read_text().replace('import regex._regex as _regex', 'import _regex'))
    regex_py = dest / 'regex.py'
    regex_py.write_text(regex_py.read_text().replace('import regex._regex as _regex', 'import _regex'))
    # makesetup derives object paths from source basenames and does not handle
    # absolute source paths well. Copy C sources into CPython's Modules dir with
    # flat unique names, while retaining the original include dir for headers.
    shutil.copy2(src / '_regex.c', SRC / 'Modules/wasi_regex.c')
    shutil.copy2(src / '_regex_unicode.c', SRC / 'Modules/wasi_regex_unicode.c')

def env():
    if not (WASI_SDK / 'bin/clang').exists():
        raise SystemExit(f'WASI SDK not found at {WASI_SDK}; install wasmpy-build first')
    e = os.environ.copy()
    e['WASI_SDK_PATH'] = str(WASI_SDK)
    e['PATH'] = f'{WASMTIME.parent}:{WASI_SDK / "bin"}:{e["PATH"]}'
    return e

def setup_local_text():
    text = SETUP_LOCAL_HEADER
    rsrc = regex_source_dir() / 'regex_3'
    if (rsrc / '_regex.c').exists():
        text += '\n# Third-party native modules built as top-level builtins. Package Python\n'
        text += '# files in third-party-site patch dotted imports to these names.\n'
        # Start a new static section after the disabled block; otherwise makesetup
        # treats following module lines as disabled too.
        text += '*static*\n'
        text += f'_regex wasi_regex.c wasi_regex_unicode.c -I{rsrc}\n'
    msrc = msgpack_source_dir() / 'msgpack'
    if (msrc / '_cmsgpack.c').exists():
        if '*static*' not in text.split('xxlimited_35', 1)[-1]:
            text += '*static*\n'
        text += f'_cmsgpack wasi_cmsgpack.c -I{msrc} -I{msrc.parent}\n'
    lsrc = lxml_source_dir() / 'src/lxml'
    if (lsrc / 'etree.c').exists():
        if '*static*' not in text.split('xxlimited_35', 1)[-1]:
            text += '*static*\n'
        incs = f'-I{lsrc} -I{lsrc / "includes"} -I{THIRD_PARTY_PREFIX / "include"} -I{THIRD_PARTY_PREFIX / "include/libxml2"}'
        libs = f'{THIRD_PARTY_PREFIX / "lib/libexslt.a"} {THIRD_PARTY_PREFIX / "lib/libxslt.a"} {THIRD_PARTY_PREFIX / "lib/libxml2.a"}'
        text += f'_lxml_etree wasi_lxml_etree.c {incs} {libs}\n'
        text += f'_lxml_objectify wasi_lxml_objectify.c {incs} {libs}\n'
        text += f'_lxml_elementpath wasi_lxml_elementpath.c {incs}\n'
        text += f'_lxml_builder wasi_lxml_builder.c {incs} {libs}\n'
        text += f'_lxml_sax wasi_lxml_sax.c {incs} {libs}\n'
    psrc = pillow_source_dir() / 'src'
    if (psrc / '_imaging.c').exists():
        if '*static*' not in text.split('xxlimited_35', 1)[-1]:
            text += '*static*\n'
        prefix = THIRD_PARTY_PREFIX
        pinc = f'-I{psrc} -I{psrc / "libImaging"} -I{prefix / "include"} -I{prefix / "include/freetype2"} -I{prefix / "include/openjpeg-2.5"}'
        pdefs = '-DHAVE_LIBZ -DHAVE_LIBJPEG -DHAVE_LIBTIFF -DHAVE_OPENJPEG'
        pobjs = ' '.join(staged for _, staged in pillow_c_sources())
        core_libs = ' '.join(str(prefix / f'lib/{lib}') for lib in [
            'libtiff.a', 'libopenjp2.a', 'libjpeg.a', 'libpng16.a', 'liblzma.a', 'libz.a', 'libbz2.a'
        ])
        text += f'_imaging {pobjs} {pinc} {pdefs} {core_libs}\n'
        ft_libs = ' '.join(str(prefix / f'lib/{lib}') for lib in ['libfreetype.a', 'libpng16.a', 'libz.a', 'libbz2.a'])
        text += f'_imagingft wasi_pil_imagingft.c {pinc} {ft_libs}\n'
        text += f'_imagingcms wasi_pil_imagingcms.c {pinc} {prefix / "lib/liblcms2.a"}\n'
        webp_libs = ' '.join(str(prefix / f'lib/{lib}') for lib in ['libwebpdemux.a', 'libwebpmux.a', 'libwebp.a', 'libsharpyuv.a'])
        text += f'_webp wasi_pil_webp.c {pinc} {webp_libs}\n'
        avif_libs = ' '.join(str(prefix / f'lib/{lib}') for lib in ['libavif.a', 'libaom.a', 'libyuv.a', 'libsharpyuv.a'])
        text += f'_avif wasi_pil_avif.c {pinc} {avif_libs}\n'
        text += f'_imagingmath wasi_pil_imagingmath.c {pinc}\n'
        text += f'_imagingmorph wasi_pil_imagingmorph.c {pinc}\n'
    return text

def write_setup_local():
    (SRC / 'Modules/Setup.local').write_text(setup_local_text())
    bcopy = SRC / 'builddir/wasi/Modules/Setup.local'
    if bcopy.parent.exists():
        bcopy.write_text(setup_local_text())

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--clean', action='store_true', help='clean CPython wasm build before building')
    args = ap.parse_args()
    ensure_source(); ensure_wasmtime(); ensure_regex_source(); ensure_msgpack_source(); ensure_lxml_source(); ensure_pillow_source(); stage_regex_package(); stage_msgpack_package(); stage_lxml_package(); stage_pillow_package(); write_setup_local()
    base_env = env()
    host_cmd = [sys.executable, './Tools/wasm/wasm_build.py']
    if args.clean:
        host_cmd.append('--clean')
    host_cmd += ['build', 'build']
    run(host_cmd, cwd=SRC, env=base_env)

    target_env = base_env.copy()
    if THIRD_PARTY_PREFIX.exists():
        inc = THIRD_PARTY_PREFIX / 'include'; lib = THIRD_PARTY_PREFIX / 'lib'; pc = lib / 'pkgconfig'
        target_env['CPPFLAGS'] = f'-I{inc} ' + target_env.get('CPPFLAGS', '')
        target_env['LDFLAGS'] = f'-L{lib} -L{WASI_SDK / "share/wasi-sysroot/lib/wasm32-wasip1"} ' + target_env.get('LDFLAGS', '')
        target_env['PKG_CONFIG_PATH'] = str(pc)
    # lxml's generated etree.c is enormous; compiling it at CPython's default
    # -O3 exhausts this VM. Keep target C extension optimization modest.
    target_env['CFLAGS'] = '-O0 -g0 -mllvm -wasm-enable-sjlj -D_WASI_EMULATED_PROCESS_CLOCKS ' + target_env.get('CFLAGS', '')
    target_env['LDFLAGS'] = target_env.get('LDFLAGS', '') + ' -mllvm -wasm-enable-sjlj -lsetjmp -lwasi-emulated-process-clocks'
    target_env['MAKEFLAGS'] = '-j1'
    if args.clean:
        shutil.rmtree(SRC / 'builddir/wasi', ignore_errors=True)
    run([sys.executable, './Tools/wasm/wasm_build.py', 'wasi', 'configure'], cwd=SRC, env=target_env)
    write_setup_local()
    run([sys.executable, './Tools/wasm/wasm_build.py', '--clean', 'wasi', 'compile'], cwd=SRC, env=target_env)
    print(SRC / 'builddir/wasi/python.wasm')

if __name__ == '__main__':
    main()
