#!/usr/bin/env python3
from __future__ import annotations
import argparse, os, shutil, subprocess, sys, tarfile, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORK = ROOT / 'experiments/static-wasi-python'
SRC = WORK / 'Python-3.12.0'
TGZ = WORK / 'Python-3.12.0.tgz'
PY_URL = 'https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz'
WASMTIME = ROOT / 'experiments/wasi-python-spike/wasmtime/wasmtime-v18.0.4-x86_64-linux/wasmtime'
WASI_SDK = Path.home() / '.local/share/wasmpy-build/wasi-sdk'
THIRD_PARTY_PREFIX = WORK / 'third-party-wasi'
THIRD_PARTY_SRC = WORK / 'third-party-src'
THIRD_PARTY_BUILD = WORK / 'third-party-build'
THIRD_PARTY_SITE = WORK / 'third-party-site'
REGEX_TGZ = THIRD_PARTY_SRC / 'regex-2024.11.6.tar.gz'
REGEX_URL = 'https://files.pythonhosted.org/packages/source/r/regex/regex-2024.11.6.tar.gz'

SETUP_LOCAL_HEADER = '''# Generated by scripts/static_wasi/build_static_wasi_python.py.
# WASI target policy: no dynamic extension modules.  The Android/Chicory path
# needs one self-contained python.wasm, so third-party C extensions are added
# here as builtin/static modules instead of .so/.wasm extension files.
#
# CPython 3.12's wasm32-wasi build already makes stdlib extension modules
# static by default.  These test/limited-ABI modules are marked shared in
# Modules/Setup.stdlib.in; disable them so `make all` never invokes wasm-ld as
# a dynamic-extension linker.
*disabled*
_testimportmultiple
_testmultiphase
_testsinglephase
xxlimited
xxlimited_35
'''.rstrip() + '\n'

def run(cmd, *, cwd=None, env=None, check=True):
    print('+', ' '.join(map(str, cmd)))
    return subprocess.run(list(map(str, cmd)), cwd=cwd, env=env, check=check)

def ensure_source():
    WORK.mkdir(parents=True, exist_ok=True)
    if not TGZ.exists():
        urllib.request.urlretrieve(PY_URL, TGZ)
    if not SRC.exists():
        with tarfile.open(TGZ) as t:
            t.extractall(WORK)

def ensure_wasmtime():
    if WASMTIME.exists():
        return
    run([sys.executable, str(ROOT / 'experiments/wasi_python_probe.py')], check=False)
    if not WASMTIME.exists():
        raise SystemExit(f'wasmtime not found at {WASMTIME}')

def regex_source_dir() -> Path:
    return THIRD_PARTY_BUILD / 'regex-2024.11.6'

def ensure_regex_source():
    THIRD_PARTY_SRC.mkdir(parents=True, exist_ok=True)
    THIRD_PARTY_BUILD.mkdir(parents=True, exist_ok=True)
    if not REGEX_TGZ.exists():
        urllib.request.urlretrieve(REGEX_URL, REGEX_TGZ)
    dest = regex_source_dir()
    if not dest.exists():
        with tarfile.open(REGEX_TGZ) as t:
            t.extractall(THIRD_PARTY_BUILD)

def stage_regex_package():
    src = regex_source_dir() / 'regex_3'
    dest = THIRD_PARTY_SITE / 'regex'
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, dest, ignore=shutil.ignore_patterns('*.c', '*.h', 'test_regex.py', '__pycache__'))
    core = dest / '_regex_core.py'
    core.write_text(core.read_text().replace('import regex._regex as _regex', 'import _regex'))
    regex_py = dest / 'regex.py'
    regex_py.write_text(regex_py.read_text().replace('import regex._regex as _regex', 'import _regex'))
    # makesetup derives object paths from source basenames and does not handle
    # absolute source paths well. Copy C sources into CPython's Modules dir with
    # flat unique names, while retaining the original include dir for headers.
    shutil.copy2(src / '_regex.c', SRC / 'Modules/wasi_regex.c')
    shutil.copy2(src / '_regex_unicode.c', SRC / 'Modules/wasi_regex_unicode.c')

def env():
    if not (WASI_SDK / 'bin/clang').exists():
        raise SystemExit(f'WASI SDK not found at {WASI_SDK}; install wasmpy-build first')
    e = os.environ.copy()
    e['WASI_SDK_PATH'] = str(WASI_SDK)
    e['PATH'] = f'{WASMTIME.parent}:{WASI_SDK / "bin"}:{e["PATH"]}'
    return e

def setup_local_text():
    text = SETUP_LOCAL_HEADER
    rsrc = regex_source_dir() / 'regex_3'
    if (rsrc / '_regex.c').exists():
        text += '\n# Third-party native modules built as top-level builtins. Package Python\n'
        text += '# files in third-party-site patch dotted imports to these names.\n'
        # Start a new static section after the disabled block; otherwise makesetup
        # treats following module lines as disabled too.
        text += '*static*\n'
        text += f'_regex wasi_regex.c wasi_regex_unicode.c -I{rsrc}\n'
    return text

def write_setup_local():
    (SRC / 'Modules/Setup.local').write_text(setup_local_text())
    bcopy = SRC / 'builddir/wasi/Modules/Setup.local'
    if bcopy.parent.exists():
        bcopy.write_text(setup_local_text())

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--clean', action='store_true', help='clean CPython wasm build before building')
    args = ap.parse_args()
    ensure_source(); ensure_wasmtime(); ensure_regex_source(); stage_regex_package(); write_setup_local()
    base_env = env()
    host_cmd = [sys.executable, './Tools/wasm/wasm_build.py']
    if args.clean:
        host_cmd.append('--clean')
    host_cmd += ['build', 'build']
    run(host_cmd, cwd=SRC, env=base_env)

    target_env = base_env.copy()
    if THIRD_PARTY_PREFIX.exists():
        inc = THIRD_PARTY_PREFIX / 'include'; lib = THIRD_PARTY_PREFIX / 'lib'; pc = lib / 'pkgconfig'
        target_env['CPPFLAGS'] = f'-I{inc} ' + target_env.get('CPPFLAGS', '')
        target_env['LDFLAGS'] = f'-L{lib} ' + target_env.get('LDFLAGS', '')
        target_env['PKG_CONFIG_PATH'] = str(pc)
    if args.clean:
        shutil.rmtree(SRC / 'builddir/wasi', ignore_errors=True)
    run([sys.executable, './Tools/wasm/wasm_build.py', 'wasi', 'configure'], cwd=SRC, env=target_env)
    write_setup_local()
    run([sys.executable, './Tools/wasm/wasm_build.py', '--clean', 'wasi', 'compile'], cwd=SRC, env=target_env)
    print(SRC / 'builddir/wasi/python.wasm')

if __name__ == '__main__':
    main()
